name: VS2022

on:
  push:
    paths-ignore:
      - '_sign.cmd'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'
      - 'icons/**'
      - '**.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '_sign.cmd'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'
      - 'icons/**'
      - '**.md'

env:
  FRIENDLY_NAME: nvBrightness
  CONFIGURATION: Release

jobs:
  VS2022-Build:
    runs-on: windows-latest

    strategy:
      matrix:
        TARGET_PLATFORM: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build
      shell: cmd
      run: |
        msbuild ${{ env.FRIENDLY_NAME }}.sln /m /p:Configuration=${{ env.CONFIGURATION }},Platform=${{ matrix.TARGET_PLATFORM }},ForceImportBeforeCppTargets=%GITHUB_WORKSPACE%\.vs\Generate.PDB.props
        move .\${{ matrix.TARGET_PLATFORM }}\Release\${{ env.FRIENDLY_NAME }}.exe .\${{ env.FRIENDLY_NAME }}.exe
        move .\${{ matrix.TARGET_PLATFORM }}\Release\${{ env.FRIENDLY_NAME }}.pdb .\${{ env.FRIENDLY_NAME }}.pdb

    - name: Display SHA-256
      run: sha256sum ./*.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'push' }}
      with:
        name: ${{ matrix.TARGET_PLATFORM }}
        path: |
          ./*.exe
          ./*.pdb
